- file:
    path: "/home/ec2-user/{{item}}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0755
  with_items:
    - .vim
    - .vim/tmp
    - .vim/bundle

- yum:
    name: "{{item}}"
    state: latest
  with_items:
    - git
    - ctags
    - gcc
    - vim
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
    - tmux
    - libffi-devel

- git:
    repo: "{{item.repo}}"
    dest: "{{item.dest}}" 
    clone: yes
  become: no
  with_items:
      - { repo: "https://github.com/Shougo/neobundle.vim", dest: "/home/ec2-user/.vim/bundle/neobundle.vim" }
      - { repo: "https://github.com/yyuu/pyenv.git", dest: "/home/ec2-user/.pyenv" }
      - { repo: "https://github.com/yyuu/pyenv-virtualenv.git", dest: "/home/ec2-user/.pyenv/plugins/pyenv-virtualenv" }
      - { repo: "https://github.com/vim/vim.git", dest: "/home/ec2-user/vim" }
      - { repo: "https://github.com/sstephenson/rbenv.git", dest: "/home/ec2-user/.rbenv" }
      - { repo: "https://github.com/sstephenson/ruby-build.git", dest: "/home/ec2-user/.rbenv/plugins/ruby-build" }

- copy:
    src: "{{item}}" 
    dest: "/home/ec2-user/{{item}}"
    owner: ec2-user
    group: ec2-user
    mode: 0644
  with_items:
      - .vimrc
      - .tmux.conf

- blockinfile:
    dest: /home/ec2-user/.bash_profile
    content: |
        export PYENV_ROOT=$HOME/.pyenv
        export PATH=$PYENV_ROOT/bin:$PATH
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(rbenv init -)"
        export HISTTIMEFORMAT=%Y-%m-%dT%T%z
        export HISTCONTROL=ignoreboth
        export HISTSIZE=20000
        export HISTFILESIZE=20000
        export HISTIGNORE=ls:fg:bg:ll:history
  become: no

- shell: source ~/.bash_profile; CONFIGURE_OPTS="--enable-shared" pyenv install -s {{item}}
  register: res
  changed_when: res.rc == 0 and res.stderr
  failed_when: res.rc != 0
  become: no
  with_items:
      - 2.7.13
      - 3.6.2

- shell: source ~/.bash_profile; pyenv global 2.7.13 3.6.2
  become: no

# - script: test.sh
#  become: no
